name: Build Docker
on: push
jobs:
    docker:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Determine Tag
              id: vars
              run: |
                  echo "::set-output name=ref::$( basename ${{ github.ref }} )"

            - name: Build
              uses: docker/build-push-action@v2
              with:
                  tags: |
                      snowblossom/snowblossom:${{ steps.vars.outputs.ref }},
                      snowblossom/snowblossom:${{ steps.vars.outputs.ref }}-${{ github.sha }},
                      snowblossom/snowblossom:${{ github.sha }}
