name: Build Docker Image
on: push

env:
    DOCKER_REPOSITORY: snowblossom/snowblossom

jobs:
    docker:
        name: Build Docker Image
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Determine Meta
              run: |
                  REF="${GITHUB_REF##*/}" >> $GITHUB_ENV
                  TAGS=\
                  $DOCKER_REPOSITORY:$REF
                  if [[ "$GITHUB_REF" == *"tags"* ]]; then
                      TAGS=$TAGS,$DOCKER_REPOSITORY:latest
                  fi
                  echo "TAGS=$TAGS" >> $GITHUB_ENV

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and Push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  cache-from: type=registry,ref=${{ env.DOCKER_REPOSITORY }}:${{ env.REF }}
                  cache-to: type=inline
                  tags: ${{ env.TAGS }}
