name: Build Docker Image
on: push
jobs:
    docker:
        name: "Build Docker Image"
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Determine Tag
              id: vars
              run: echo "::set-output name=ref::$( basename ${{ github.ref }} )"

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  cache-from: type=registry,ref=snowblossom/snowblossom:${{ steps.vars.outputs.ref }}
                  cache-to: type=inline
                  tags: |
                      snowblossom/snowblossom:${{ steps.vars.outputs.ref }},
                      snowblossom/snowblossom:${{ steps.vars.outputs.ref }}-${{ github.sha }},
                      snowblossom/snowblossom:${{ github.sha }}
