name: Build Docker Image
on: push

env:
    REPOSITORY: snowblossom/snowblossom

jobs:
    docker:
        name: Build Docker Image
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2

            - name: Determine Meta
              run: |
                  REF="${GITHUB_REF##*/}" >> $GITHUB_ENV
                  TAGS=\
                  $REPOSITORY:$REF,\
                  $REPOSITORY:$GITHUB_SHA,\
                  $REPOSITORY:$REF-$GITHUB_SHA
                  [[ "$GITHUB_REF" == *"tags"* ]] && TAGS=$TAGS,$REPOSITORY:latest
                  echo "TAGS=$TAGS" >> $GITHUB_ENV

            - if: ${{ boolean(secrets.DOCKERHUB_USERNAME) }}
              name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and Push
              uses: docker/build-push-action@v2
              with:
                  push: ${{ boolean( secrets.DOCKERHUB_USERNAME) }}
                  cache-from: type=registry,ref=${{ env.REPOSITORY }}:${{ env.REF }}
                  cache-to: type=inline
                  tags: ${{ env.TAGS }}
  
