name: Build Docker
on: push
jobs:
    docker:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Determine Tag
              run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

            - name: Build
              uses: docker/build-push-action@v2
              with:
                  tags:
                      - snowblossom/snowblossom:$GITHUB_REF
                      - snowblossom/snowblossom:$GITHUB_REF-$GITHUB_SHA_SHORT
                      - snowblossom/snowblossom:$GITHUB_SHA_SHORT
